#!/usr/bin/env python3
"""Generate the CLDR currency tables under src/ from supplemental data.

Usage: gen-currency-tables.py [supplementalData.xml]

region-currency-table.inc
    For each region, keeps the first currency in document order that is still
    legal tender (no `to` date, tender != "false"); CLDR document order encodes
    preference. Regions with no current tender (e.g. AQ, dissolved countries)
    are omitted.

currency-digits-table.inc
    Minor unit digits per currency, e.g. JPY has none and BHD has three.
    `cashDigits`/`cashRounding` are ignored: they describe physical coinage,
    not the amounts a calculator deals in.
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    xml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "extra/supplementalData.xml"

    currency_data = ET.parse(xml_path).getroot().find("currencyData")
    table = {}
    for region in currency_data.findall("region"):
        code = region.get("iso3166")
        for cur in region.findall("currency"):
            if cur.get("to") is None and cur.get("tender") != "false":
                table[code] = cur.get("iso4217")
                break

    for code, currency in table.items():
        assert len(code) == 2 and code.isalpha() and code.isupper(), code
        assert len(currency) == 3 and currency.isupper(), currency

    def banner():
        return [
            f"// Generated by scripts/{Path(__file__).name} from CLDR currencyData",
            f"// ({xml_path.name}). Do not edit by hand.",
        ]

    out_path = ROOT / "src/region-currency-table.inc"
    lines = banner() + ["constexpr RegionCurrency kRegionCurrencyTable[] = {"]
    for code in sorted(table):
        lines.append(f'    {{"{code}", "{table[code]}"}},')
    lines += ["};", ""]
    out_path.write_text("\n".join(lines))
    print(f"{len(table)} regions -> {out_path}")

    digits = {}
    default = 2
    for info in currency_data.find("fractions").findall("info"):
        code = info.get("iso4217")
        if code == "DEFAULT":
            default = int(info.get("digits"))
            continue
        digits[code] = int(info.get("digits"))

    for code, n in digits.items():
        assert len(code) == 3 and code.isupper(), code
        assert 0 <= n <= 9, (code, n)

    out_path = ROOT / "src/currency-digits-table.inc"
    lines = banner() + [
        f"constexpr int kDefaultCurrencyDigits = {default};",
        "",
        "constexpr CurrencyDigits kCurrencyDigitsTable[] = {",
    ]
    for code in sorted(digits):
        lines.append(f'    {{"{code}", {digits[code]}}},')
    lines += ["};", ""]
    out_path.write_text("\n".join(lines))
    print(f"{len(digits)} currencies -> {out_path}")


main()
