#!/usr/bin/env python3
"""Generate src/region-currency-table.inc from CLDR supplemental data.

Usage: gen-region-currency.py [supplementalData.xml] [output.inc]

For each region, keeps the first currency in document order that is still
legal tender (no `to` date, tender != "false"); CLDR document order encodes
preference. Regions with no current tender (e.g. AQ, dissolved countries)
are omitted.
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    xml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "extra/supplementalData.xml"
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "src/region-currency-table.inc"

    currency_data = ET.parse(xml_path).getroot().find("currencyData")
    table = {}
    for region in currency_data.findall("region"):
        code = region.get("iso3166")
        for cur in region.findall("currency"):
            if cur.get("to") is None and cur.get("tender") != "false":
                table[code] = cur.get("iso4217")
                break

    for code, currency in table.items():
        assert len(code) == 2 and code.isalpha() and code.isupper(), code
        assert len(currency) == 3 and currency.isupper(), currency

    lines = [
        f"// Generated by scripts/{Path(__file__).name} from CLDR currencyData",
        f"// ({xml_path.name}). Do not edit by hand.",
        "constexpr RegionCurrency kRegionCurrencyTable[] = {",
    ]
    for code in sorted(table):
        lines.append(f'    {{"{code}", "{table[code]}"}},')
    lines += ["};", ""]
    out_path.write_text("\n".join(lines))
    print(f"{len(table)} regions -> {out_path}")


main()
