#!/usr/bin/env python3
"""Generate src/numen/gen/tz-links.inc, the IANA timezone link -> canonical zone
table, from the tzdata source files (https://www.iana.org/time-zones, public domain).

Usage: gen-tz-links.py [--tzdata DIR]

The latest tzdata tarball is downloaded into DIR (default .cache/tzdata) unless
already there. Only the generated file is committed.

Backends that read the OS zoneinfo directory (HowardHinnant/date on Apple) see
links as zones of their own; this table restores the distinction.
"""
import sys
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
URL = "https://data.iana.org/time-zones/tzdata-latest.tar.gz"
OUT = ROOT / "src/numen/gen/tz-links.inc"


# the files a default tzdata build compiles (TDATA in its Makefile): backzone is left out
SOURCES = ["africa", "antarctica", "asia", "australasia", "europe", "northamerica", "southamerica",
           "etcetera", "factory", "backward"]


def fetch(raw):
    raw.mkdir(parents=True, exist_ok=True)
    tarball = raw / "tzdata-latest.tar.gz"
    if not tarball.exists():
        print(f"downloading {URL}")
        urllib.request.urlretrieve(URL, tarball)
    with tarfile.open(tarball) as tar:
        sources = [tar.extractfile(name).read().decode() for name in SOURCES]
        version = tar.extractfile("version").read().decode().strip()
    return sources, version


def main():
    raw = Path(sys.argv[2]) if sys.argv[1:2] == ["--tzdata"] else ROOT / ".cache/tzdata"
    sources, version = fetch(raw)
    links = sorted({
        (fields[2], fields[1])
        for source in sources
        for line in source.splitlines()
        if line.startswith("Link")
        for fields in [line.split("#")[0].split()]
    })
    lines = [
        f"// Generated by scripts/gen-tz-links.py from IANA tzdata {version}.",
        "// Do not edit by hand.",
        "constexpr TzLink kTzLinks[] = {",
        *(f'    {{"{name}", "{target}"}},' for name, target in links),
        "};",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"{len(links)} links ({version}) -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
