#!/usr/bin/env python3
"""Generate the CLDR region currency table under src/numen/gen/ from
supplemental data.

Usage: gen-currency-tables.py [supplementalData.xml]

region-currency-table.inc
    For each region, keeps the first currency in document order that is still
    legal tender (no `to` date, tender != "false"); CLDR document order encodes
    preference. Regions with no current tender (e.g. AQ, dissolved countries)
    are omitted.

Minor unit digits are not generated: every currency the calculator knows is
declared in src/numen/builtin-units.cpp with its `decimals` field, and the
ones only a currency provider knows about fall back to a fixed precision.
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    xml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "extra/supplementalData.xml"

    currency_data = ET.parse(xml_path).getroot().find("currencyData")
    table = {}
    for region in currency_data.findall("region"):
        code = region.get("iso3166")
        for cur in region.findall("currency"):
            if cur.get("to") is None and cur.get("tender") != "false":
                table[code] = cur.get("iso4217")
                break

    for code, currency in table.items():
        assert len(code) == 2 and code.isalpha() and code.isupper(), code
        assert len(currency) == 3 and currency.isupper(), currency

    def banner():
        return [
            f"// Generated by scripts/{Path(__file__).name} from CLDR currencyData",
            f"// ({xml_path.name}). Do not edit by hand.",
        ]

    out_path = ROOT / "src/numen/gen/region-currency-table.inc"
    lines = banner() + ["constexpr RegionCurrency kRegionCurrencyTable[] = {"]
    for code in sorted(table):
        lines.append(f'    {{"{code}", "{table[code]}"}},')
    lines += ["};", ""]
    out_path.write_text("\n".join(lines))
    print(f"{len(table)} regions -> {out_path}")


main()
